package com.example.arcana.capability;
import com.example.arcana.Arcana; import com.example.arcana.network.ArcanaNetwork; import net.minecraft.core.Direction; import net.minecraft.nbt.*; import net.minecraft.resources.ResourceLocation; import net.minecraft.server.level.ServerPlayer; import net.minecraft.world.item.*; import net.minecraftforge.common.capabilities.*; import net.minecraftforge.common.util.LazyOptional; import net.minecraftforge.event.AttachCapabilitiesEvent; import net.minecraftforge.event.entity.player.PlayerEvent; import net.minecraftforge.eventbus.api.SubscribeEvent; import net.minecraftforge.event.TickEvent;
public class ManaCapability {
 public static final Capability<ManaData> TYPE=CapabilityManager.get(new CapabilityToken<>(){}); private static final ResourceLocation KEY=Arcana.id("mana");
 @SubscribeEvent public void attach(AttachCapabilitiesEvent<net.minecraft.world.entity.Entity> e){if(e.getObject() instanceof net.minecraft.world.entity.player.Player p)e.addCapability(KEY,new Provider());}
 @SubscribeEvent public void tick(TickEvent.PlayerTickEvent e){if(e.phase==TickEvent.Phase.END&&!e.player.level().isClientSide&&e.player.tickCount%2==0)e.player.getCapability(TYPE).ifPresent(m->{m.tick();m.checkLevel(e.player.experienceLevel);if(e.player.tickCount%10==0)ArcanaNetwork.sync((ServerPlayer)e.player);});}
 @SubscribeEvent public void clone(PlayerEvent.Clone e){e.getOriginal().getCapability(TYPE).ifPresent(old->e.getEntity().getCapability(TYPE).ifPresent(now->now.load(old.save())));}
 @SubscribeEvent public void joined(PlayerEvent.PlayerLoggedInEvent e){var p=e.getEntity();if(p.level().isClientSide||!"".equals(p.getPersistentData().getString("arcana_guide_version")))return;ItemStack book=new ItemStack(Items.WRITTEN_BOOK);var tag=book.getOrCreateTag();tag.putString("title","Arcana Field Manual v0.6.0");tag.putString("author","Arcana");ListTag pages=new ListTag();
  page(pages,"ARCANA FIELD MANUAL\\n\\nWelcome, mage. This manual explains the current Arcana systems.\\n\\nV cast selected spell\\n1 / 2 / 3 choose spell\\nK open Skill Tree");
  page(pages,"MANA\\n\\nMana is shown at the lower left. You begin with 100 maximum mana and regenerate steadily.\\n\\nArcane Bolt costs 12\\nBlink costs 20\\nWard costs 18");
  page(pages,"SPELL HOTBAR\\n\\nPress 1 for Arcane Bolt, 2 for Blink, or 3 for Ward. The selected spell is shown above the hotbar. Press V to cast it.\\n\\nThe server checks every cast.");
  page(pages,"ARCANE BOLT\\n\\nA fast purple projectile that ignores gravity. It travels 32 blocks at base rank.\\n\\nBolt Range upgrades add 8 blocks. Bolt damage and piercing upgrades are planned.");
  page(pages,"BLINK\\n\\nBlink teleports you up to 12 blocks toward your crosshair. The path is checked so the destination is safer.\\n\\nBlinkstone will later improve range and cooldown.");
  page(pages,"WARD\\n\\nWard grants temporary Resistance II for protection. It costs 18 mana and has a cooldown.\\n\\nWard Sigils will later add absorption, reflection, and ally protection.");
  page(pages,"SKILL TREE\\n\\nPress K to open the Minecraft-style Arcana Skill Tree. Gain one skill point whenever you gain an XP level.\\n\\nAttunement I: +10 maximum mana.\\nArcane Bolt: +8 range.");
  page(pages,"UPGRADING\\n\\nClick a glowing node to spend one skill point. Locked nodes are future branches or require prerequisites.\\n\\nYour points and unlocked upgrades persist through death and relogging.");
  page(pages,"CRAFTED RELICS\\n\\nMana Crystal: mana progression.\\nSage's Ring: regeneration progression.\\nArcane Focus: spell power progression.\\nBlinkstone: Blink progression.\\nWard Sigil: Ward progression.");
  page(pages,"CRAFTING\\n\\nUse the README recipe artwork for the visual 3x3 patterns. The crafting table accepts the five starter recipes. More relic recipes will arrive with schools and bosses.");
  page(pages,"MULTIPLAYER\\n\\nArcana is server-authoritative. The server owns mana, cooldowns, teleporting, damage, projectiles, and skill spending. This keeps singleplayer and dedicated servers aligned.");
  page(pages,"ROADMAP\\n\\nNext: more skill nodes, functional relic bonuses, visual cooldowns, Fire and Storm schools, spell hotbar polish, rituals, bosses, and magical world structures.");
  tag.put("pages",pages);p.getInventory().add(book);p.getPersistentData().putString("arcana_guide_version","0.6.0");}
 private static void page(ListTag pages,String text){pages.add(StringTag.valueOf("{\"text\":\""+text+"\"}"));}
 public static class Provider implements ICapabilityProvider,ICapabilitySerializable<CompoundTag>{final ManaData data=new ManaData();final LazyOptional<ManaData> opt=LazyOptional.of(()->data);public <T> LazyOptional<T> getCapability(Capability<T> c,Direction d){return c==TYPE?opt.cast():LazyOptional.empty();}public CompoundTag serializeNBT(){return data.save();}public void deserializeNBT(CompoundTag t){data.load(t);}}
}
