package com.example.arcana.client;
import com.example.arcana.Arcana; import com.example.arcana.network.*; import net.minecraft.client.Minecraft; import net.minecraft.client.KeyMapping; import net.minecraft.client.gui.GuiGraphics; import net.minecraftforge.api.distmarker.*; import net.minecraftforge.client.event.*; import net.minecraftforge.eventbus.api.SubscribeEvent; import net.minecraftforge.fml.common.Mod; import org.lwjgl.glfw.GLFW;
@Mod.EventBusSubscriber(modid=Arcana.MOD_ID,value=Dist.CLIENT,bus=Mod.EventBusSubscriber.Bus.FORGE)
public class ArcanaClient { public static float mana=100; public static String selectedSpell="arcane_bolt"; public static final KeyMapping CAST=new KeyMapping("key.arcana.cast_selected",GLFW.GLFW_KEY_V,"key.categories.arcana"); public static final KeyMapping SLOT1=new KeyMapping("key.arcana.slot_1",GLFW.GLFW_KEY_1,"key.categories.arcana"); public static final KeyMapping SLOT2=new KeyMapping("key.arcana.slot_2",GLFW.GLFW_KEY_2,"key.categories.arcana"); public static final KeyMapping SLOT3=new KeyMapping("key.arcana.slot_3",GLFW.GLFW_KEY_3,"key.categories.arcana"); public static final KeyMapping TREE=new KeyMapping("key.arcana.skill_tree",GLFW.GLFW_KEY_K,"key.categories.arcana");
 @net.minecraftforge.fml.common.Mod.EventBusSubscriber(modid=Arcana.MOD_ID,bus=net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus.MOD,value=Dist.CLIENT)
 public static class ModBus { @SubscribeEvent public static void keys(net.minecraftforge.client.event.RegisterKeyMappingsEvent e){e.register(CAST);e.register(SLOT1);e.register(SLOT2);e.register(SLOT3);e.register(TREE);} @SubscribeEvent public static void render(net.minecraftforge.client.event.EntityRenderersEvent.RegisterRenderers e){e.registerEntityRenderer(com.example.arcana.entity.ArcanaEntities.ARCANE_BOLT.get(),net.minecraft.client.renderer.entity.ThrownItemRenderer::new);} }
 @SubscribeEvent public static void keys(InputEvent.Key e){if(CAST.consumeClick())ArcanaNetwork.CHANNEL.sendToServer(new CastSpellPacket(selectedSpell));if(SLOT1.consumeClick())selectedSpell="arcane_bolt";if(SLOT2.consumeClick())selectedSpell="blink";if(SLOT3.consumeClick())selectedSpell="ward";if(TREE.consumeClick())Minecraft.getInstance().setScreen(new SkillTreeScreen());}
 @SubscribeEvent public static void hud(RenderGuiEvent.Post e){GuiGraphics g=e.getGuiGraphics();int x=10,y=e.getWindow().getGuiScaledHeight()-30;g.fill(x,y,x+102,y+10,0xAA160B2E);g.fill(x+1,y+1,x+1+(int)mana,y+9,0xFF8A5CFF);g.drawString(Minecraft.getInstance().font,"Mana "+(int)mana+"/100",x,y-10,0xFFDCCBFF);int px=e.getWindow().getGuiScaledWidth()-168,py=e.getWindow().getGuiScaledHeight()/2-72;spellCard(g,px,py,1,"Arcane Bolt","12 MP",0xFFB45CFF,"arcane_bolt");spellCard(g,px,py+52,2,"Blink","20 MP",0xFF5CE7F2,"blink");spellCard(g,px,py+104,3,"Ward","18 MP",0xFF82E66A,"ward");}
 private static void spellCard(GuiGraphics g,int x,int y,int slot,String name,String cost,int color,String id){boolean selected=selectedSpell.equals(id);g.fill(x,y,x+158,y+45,0xCC100C16);g.renderOutline(x,y,158,45,selected?0xFFFFFFFF:color);g.fill(x+5,y+5,x+35,y+35,selected?color:0xFF2A2330);g.drawCenteredString(Minecraft.getInstance().font,""+slot,x+20,y+14,0xFFFFFFFF);g.drawString(Minecraft.getInstance().font,name,x+43,y+8,color);g.drawString(Minecraft.getInstance().font,cost,x+43,y+24,0xFFD8CFDF);}
}
