package com.example.arcana.client;
import com.example.arcana.Arcana; import com.example.arcana.network.*; import net.minecraft.client.Minecraft; import net.minecraft.client.KeyMapping; import net.minecraft.client.gui.GuiGraphics; import net.minecraftforge.api.distmarker.*; import net.minecraftforge.client.event.*; import net.minecraftforge.eventbus.api.SubscribeEvent; import net.minecraftforge.fml.common.Mod; import org.lwjgl.glfw.GLFW;
@Mod.EventBusSubscriber(modid=Arcana.MOD_ID,value=Dist.CLIENT,bus=Mod.EventBusSubscriber.Bus.FORGE)
public class ArcanaClient { public static float mana=100; public static final KeyMapping CAST=new KeyMapping("key.arcana.cast_arcane_bolt",GLFW.GLFW_KEY_V,"key.categories.arcana"); public static final KeyMapping BLINK=new KeyMapping("key.arcana.blink",GLFW.GLFW_KEY_B,"key.categories.arcana"); public static final KeyMapping WARD=new KeyMapping("key.arcana.ward",GLFW.GLFW_KEY_N,"key.categories.arcana");
 @net.minecraftforge.fml.common.Mod.EventBusSubscriber(modid=Arcana.MOD_ID,bus=net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus.MOD,value=Dist.CLIENT)
 public static class ModBus { @SubscribeEvent public static void keys(net.minecraftforge.client.event.RegisterKeyMappingsEvent e){e.register(CAST);e.register(BLINK);e.register(WARD);} @SubscribeEvent public static void render(net.minecraftforge.client.event.EntityRenderersEvent.RegisterRenderers e){e.registerEntityRenderer(com.example.arcana.entity.ArcanaEntities.ARCANE_BOLT.get(),net.minecraft.client.renderer.entity.ThrownItemRenderer::new);} }
 @SubscribeEvent public static void keys(InputEvent.Key e){if(CAST.consumeClick())ArcanaNetwork.CHANNEL.sendToServer(new CastSpellPacket("arcane_bolt"));if(BLINK.consumeClick())ArcanaNetwork.CHANNEL.sendToServer(new CastSpellPacket("blink"));if(WARD.consumeClick())ArcanaNetwork.CHANNEL.sendToServer(new CastSpellPacket("ward"));}
 @SubscribeEvent public static void hud(RenderGuiEvent.Post e){GuiGraphics g=e.getGuiGraphics();int x=10,y=e.getWindow().getGuiScaledHeight()-30;g.fill(x,y,x+102,y+10,0xAA160B2E);g.fill(x+1,y+1,x+1+(int)mana,y+9,0xFF8A5CFF);g.drawString(Minecraft.getInstance().font,"Mana "+(int)mana+"/100",x,y-10,0xFFDCCBFF);}
}
